version: "3.8"

services:
  frontend:
    build: ./frontend
    ports:
      - "4173:4173"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:4173
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/linkshortener
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
